Repository red-hat-data-services/notebooks, pull requests merged in 2024-10, with the labels that each got.

#388 2023a r-sync
  OWNERS
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi8-python-3.8/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi8-python-3.8/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#387 2023b r-sync
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#385 2024a r-sync
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: lgtm, approved

#389 Updated the notebook manifests with 2024b image reference
  ci/check-params-env.sh
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/commit.env
  manifests/base/commit.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/params.env
  manifests/base/params.yaml
Labels: lgtm, approved

#395 sync main branch with opendatahub: main branch
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Labels: approved

#396 sync release-2024b branch with opendatahub:2024b
  .github/workflows/runtimes-digest-updater-upstream.yaml
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: approved

#399 Fixes for the digest updater for 2024b and 2024a images releases
  .github/workflows/notebook-digest-updater.yaml
Labels: lgtm, approved, tide/merge-method-squash

#404 revert habana with removal of label opendatahub.image
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/kustomization.yaml
Labels: lgtm, approved

#406 Sync release-2024a with codeflare-sdk changes in upstream ODH notebook:2024a
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: approved

#407 update runtime-image of commit 9d2af21 with codeflare-sdk changes
  jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Labels: approved

#408 Include new set of 2024.1 images of commit 636b66d for codeflare-sdk
  manifests/base/commit.env
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/params.env
Labels: approved

#410 [GHA] Pin kustomize version we use in our test to the particular version
  .github/workflows/code-quality.yaml
Labels: lgtm, approved

#400 Remove Habana from manifests and repository docs
  docs/workbenches.md
  manifests/base/jupyter-habana-notebook-imagestream.yaml
Labels: lgtm, approved

#413 R-sync release-2024b
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/code-quality.yaml
  .github/workflows/notebooks-digest-updater-upstream.yaml
  ci/check-params-env.sh
  codeserver/ubi9-python-3.11/run-code-server.sh
  codeserver/ubi9-python-3.9/run-code-server.sh
  intel/runtimes/ml/ubi9-python-3.11/Pipfile
  intel/runtimes/ml/ubi9-python-3.11/Pipfile.lock
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/intel/ml/ubi9-python-3.11/Pipfile
  jupyter/intel/ml/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/minimal/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/test/test_notebook.ipynb
  manifests/base/README.md
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#414 sync the main branch with opendatahub main branch
  .github/workflows/build-notebooks-TEMPLATE.yaml
  .github/workflows/code-quality.yaml
  codeserver/ubi9-python-3.11/run-code-server.sh
  codeserver/ubi9-python-3.9/run-code-server.sh
  intel/runtimes/ml/ubi9-python-3.11/Pipfile
  intel/runtimes/ml/ubi9-python-3.11/Pipfile.lock
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.gpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  intel/runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/intel/ml/ubi9-python-3.11/Pipfile
  jupyter/intel/ml/ubi9-python-3.11/Pipfile.lock
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/pytorch/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.gpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.cpu
  jupyter/intel/tensorflow/ubi9-python-3.11/Pipfile.lock.gpu
  jupyter/minimal/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/test/test_notebook.ipynb
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/test/test_notebook.ipynb
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
Labels: lgtm, approved

#418 Update the annotation with elyra and codeflare-sdk updated
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved

#411 Set opendatahub.io/notebook-image to false instead of removing it
  manifests/base/jupyter-habana-notebook-imagestream.yaml
Labels: lgtm, approved

#420 [RHOAI-2.10] Deactivate Habana notebook from manifests and repository docs
  docs/workbenches.md
  manifests/base/jupyter-habana-notebook-imagestream.yaml
Labels: lgtm, approved

#421 [RHOAI-2.13] Deactivate Habana notebook from manifests and repository docs
  docs/workbenches.md
  manifests/base/jupyter-habana-notebook-imagestream.yaml
Labels: lgtm, approved

#422 [RHOAIENG-15012] fix the version of codeflare-sdk shown for 2024.1
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved
