Repository red-hat-data-services/notebooks, pull requests merged in 2024-06, with the labels that each got.

#258 RHOAIENG-8255: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location
  codeserver/ubi9-python-3.9/Dockerfile
  rstudio/c9s-python-3.9/Dockerfile
  rstudio/rhel9-python-3.9/Dockerfile
Labels: lgtm

#260 [rhoai-2.10] RHOAIENG-8255: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location
  codeserver/ubi9-python-3.9/Dockerfile
  rstudio/c9s-python-3.9/Dockerfile
  rstudio/rhel9-python-3.9/Dockerfile
Labels: lgtm

#262 [CI] Add `kubectl kustomize` run to check our manifests definition
  .github/workflows/code-quality.yaml
  ci/hadolint-config.yaml
Labels: lgtm, approved

#264 Run the static code checks on push and when manually triggered
  .github/workflows/code-quality.yaml
Labels: lgtm, approved

#238 Clean github workflow for the red-hat-data-services notebooks
  .github/workflows/notebook-digest-updater.yaml
  .github/workflows/piplock-renewal-2024a.yml
  .github/workflows/sec-scan.yml
Labels: approved

#273 [release-2024a] Cherry pick #179, #253 and #254 to release-2024a
  base/rhel9-python-3.9/Dockerfile
  ci/check-params-env.sh
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/base/params.yaml
  rstudio/rhel9-python-3.9/Dockerfile
Labels: lgtm, approved

#276 [2023b] RHOAIENG-8299, RHOAIENG-8255, RHOAIENG-8740: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm and CentOS Stream 8 download locations
  rstudio/rhel9-python-3.9/Dockerfile
Labels: lgtm, approved

#278 Replace fcgi with supervisord on rstudio rhel flavor
  rstudio/rhel9-python-3.9/Dockerfile
  rstudio/rhel9-python-3.9/run-rstudio.sh
  rstudio/rhel9-python-3.9/supervisord/supervisord.conf
Labels: lgtm, approved
