Repository red-hat-data-services/notebooks, pull requests merged in 2024-11, with the labels that each got.

#424 [RHOAIENG-14585] Add rhel9 based CUDA Python 3.11 image dockerfile
  cuda/rhel9-python-3.11/Dockerfile
  cuda/rhel9-python-3.11/NGC-DL-CONTAINER-LICENSE
  cuda/rhel9-python-3.11/cuda.repo-x86_64
  manifests/base/cuda-rstudio-buildconfig.yaml
  manifests/base/rstudio-buildconfig.yaml
Labels: lgtm, approved

#426 Sync `rhoai:release-2024a` from `odh:2024a`
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Labels: approved

#428 Updated the runtime-images for 2024a with commit 2e29fc6
  jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Labels: lgtm

#433 [RHOAIENG-15710] fix the version of codeflare-sdk shown for 2024.1
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved

#434 [RHOAIENG-14520] Change supervisord files location for rhel images
  rstudio/rhel9-python-3.11/supervisord/supervisord.conf
  rstudio/rhel9-python-3.9/supervisord/supervisord.conf
Labels: lgtm, approved

#435 Fix the annotation for ROCm in tensorflow image
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved
