Repository red-hat-data-services/notebooks, pull requests merged in 2024-08, with the labels that each got.

#345 [main] sync main from opendatahub-io:main
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: ok-to-test

#350 Update branch for the RStudio build config definitions
  manifests/base/cuda-rstudio-buildconfig.yaml
  manifests/base/rstudio-buildconfig.yaml
Labels: lgtm, approved

#352 [2024a] release-2024a from opendatahub-io:2024a
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  README.md
  ci/cached-builds/dev_null_container_registry.go
  ci/cached-builds/insecure_localhost_registry.conf
  jupyter/datascience/ubi9-python-3.9/Dockerfile
  jupyter/minimal/ubi8-python-3.8/Dockerfile
  jupyter/minimal/ubi9-python-3.9/Dockerfile
  jupyter/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/de-vendor-torch.sh
  jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/trustyai/ubi9-python-3.9/Dockerfile
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  rocm/ubi9-python-3.9/Dockerfile
  runtimes/datascience/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/datascience/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/minimal/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/minimal/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/pytorch/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-pytorch/ubi9-python-3.9/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/de-vendor-torch.sh
  runtimes/rocm-pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/tensorflow/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  tests/test_main.py
Labels: ok-to-test

#356 RHOAIENG-11087: Remove the installation of packages from bootstrapper.py
  .github/workflows/build-notebooks-TEMPLATE.yaml
  Makefile
  README.md
  ci/cached-builds/dev_null_container_registry.go
  ci/cached-builds/insecure_localhost_registry.conf
  jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
  jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
  jupyter/datascience/ubi9-python-3.9/Dockerfile
  jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
  jupyter/minimal/ubi8-python-3.8/Dockerfile
  jupyter/minimal/ubi9-python-3.9/Dockerfile
  jupyter/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
  jupyter/rocm/pytorch/ubi9-python-3.9/de-vendor-torch.sh
  jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/tensorflow/ubi9-python-3.9/Dockerfile
  jupyter/trustyai/ubi9-python-3.9/Dockerfile
  manifests/base/commit.env
  manifests/base/params.env
  runtimes/datascience/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/datascience/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/minimal/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/minimal/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/pytorch/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-pytorch/ubi9-python-3.9/Dockerfile
  runtimes/rocm-pytorch/ubi9-python-3.9/de-vendor-torch.sh
  runtimes/rocm-pytorch/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/rocm-tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  runtimes/tensorflow/ubi8-python-3.8/utils/bootstrapper.py
  runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py
  tests/test_main.py
Labels: approved

#351 [CI] remove the workaround for the Habana 1.10 image check
  ci/check-params-env.sh
Labels: lgtm, approved

#360 Update image digest and runtime GHAs to include the new ROCm changes
  .github/workflows/notebook-digest-updater.yaml
  .github/workflows/runtimes-digest-updater.yaml
  manifests/base/commit.env
  manifests/base/params.env
Labels: lgtm

#363 [release-2024a] sync release-2024a branch with upstream/2024a
  .github/workflows/code-quality.yaml
  README.md
  habana/1.10.0/ubi8-python-3.8/Pipfile.lock
  habana/1.13.0/ubi8-python-3.8/Pipfile.lock
  intel/runtimes/ml/ubi9-python-3.9/Pipfile
  intel/runtimes/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi8-python-3.8/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/Pipfile
  jupyter/datascience/ubi9-python-3.9/Pipfile.lock
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
  jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
  jupyter/intel/ml/ubi9-python-3.9/Pipfile
  jupyter/intel/ml/ubi9-python-3.9/Pipfile.lock
  jupyter/minimal/ubi8-python-3.8/Pipfile.lock
  jupyter/minimal/ubi9-python-3.9/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.9/Pipfile
  jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.9/Pipfile
  jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.9/Pipfile
  jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-habana-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml
  runtimes/datascience/ubi8-python-3.8/Pipfile.lock
  runtimes/datascience/ubi9-python-3.9/Pipfile
  runtimes/datascience/ubi9-python-3.9/Pipfile.lock
  runtimes/minimal/ubi8-python-3.8/Pipfile.lock
  runtimes/minimal/ubi9-python-3.9/Pipfile.lock
  runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.9/Pipfile
  runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.9/Pipfile.lock
  runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.9/Pipfile
  runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
  scripts/README.md
  scripts/new_python_based_image.py
  scripts/update_library_version.sh
Labels: lgtm

#331 [fix] hadolint warnings to base and rstudio Dockerfiles
  base/rhel9-python-3.9/Dockerfile
  rstudio/rhel9-python-3.9/Dockerfile
Labels: lgtm, approved

#369 Update the kfp package version in image manifest to match the reality
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Labels: lgtm, approved
