Repository red-hat-data-services/notebooks, pull requests merged in 2025-09, with the labels that each got.

#1522 Update .konflux dockerfiles to comply with ARGs
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
Labels: review-requested

#1525 Sync downstream main from upstream main
  Makefile
  ci/cached-builds/gen_gha_matrix_jobs.py
  jupyter/minimal/ubi9-python-3.12/build-args/cpu.conf
  jupyter/utils/install_pdf_deps.sh
  runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
  runtimes/datascience/ubi9-python-3.12/pylock.toml
  runtimes/datascience/ubi9-python-3.12/pyproject.toml
  scripts/generate_pull_request_pipelineruns.py
Labels: review-requested

#1527 [2.24] cherry-picks for test-only gha stuff that I want to see everything running to green when fixing the 2.24 blockers
  .github/workflows/build-notebooks-TEMPLATE.yaml
Labels: review-requested

#1524 [2.24] RHOAIENG-33414: remove gpg-pubkey RPMs from the datascience container images
  codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
Labels: lgtm, approved, tide/merge-method-squash, review-requested

#1533 Update odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v2-25-pu…
  .tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v2-25-push.yaml
Labels: review-requested

#1537 changing the pipelineref order
  .tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-v2-25-push.yaml
Labels: review-requested

#1542 fix typo in dockerfile path for a few konflux pull request pipelineruns
  .gitignore
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-pull-request.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py311-pull-request.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py312-pull-request.yaml
Labels: review-requested

#1546 follow up for RHOAIENG-33169: remove MSSQL Client installation and related configurations from Dockerfiles
  jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: review-requested

#1548 Drop 3.11 workbenches pipelines
  .tekton/odh-pipeline-runtime-datascience-cpu-py311-v2-25-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-v2-25-pull-request.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-v2-25-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py311-v2-25-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py311-v2-25-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py311-v2-25-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py311-v2-25-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-v2-25-pull-request.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py311-v2-25-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py311-v2-25-push.yaml
Labels: review-requested

#1566 Sync `rhds:main` from `odh:main`
  .tekton/odh-base-image-cuda-12-8-py312-c9s-pull-request.yaml
  .tekton/odh-base-image-cuda-12-8-py312-c9s-push.yaml
  .tekton/odh-base-image-cuda-12-8-py312-ubi9-pull-request.yaml
  .tekton/odh-base-image-cuda-12-8-py312-ubi9-push.yaml
  .tekton/odh-base-image-rocm-6-4-py312-c9s-pull-request.yaml
  .tekton/odh-base-image-rocm-6-4-py312-c9s-push.yaml
  .tekton/odh-base-image-rocm-6-4-py312-ubi9-pull-request.yaml
  .tekton/odh-base-image-rocm-6-4-py312-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml
  base-images/cuda/12.8/c9s-python-3.12/Dockerfile.cuda
  base-images/cuda/12.8/cuda-repos/NGC-DL-CONTAINER-LICENSE
  base-images/cuda/12.8/cuda-repos/cuda.repo-amd64
  base-images/cuda/12.8/cuda-repos/cuda.repo-arm64
  base-images/cuda/12.8/ubi9-python-3.12/Dockerfile.cuda
  codeserver/ubi9-python-3.12/pylock.toml
  codeserver/ubi9-python-3.12/pyproject.toml
  jupyter/datascience/ubi9-python-3.12/pylock.toml
  jupyter/datascience/ubi9-python-3.12/pyproject.toml
  jupyter/minimal/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/pylock.toml
  jupyter/pytorch+llmcompressor/ubi9-python-3.12/pyproject.toml
  jupyter/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pylock.toml
  jupyter/rocm/pytorch/ubi9-python-3.12/pyproject.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/rocm/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/tensorflow/ubi9-python-3.12/pylock.toml
  jupyter/tensorflow/ubi9-python-3.12/pyproject.toml
  jupyter/trustyai/ubi9-python-3.12/pylock.toml
  jupyter/trustyai/ubi9-python-3.12/pyproject.toml
  manifests/base/code-server-notebook-imagestream.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-llmcompressor-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  rstudio/c9s-python-3.11/pyproject.toml
  rstudio/rhel9-python-3.11/pyproject.toml
  runtimes/datascience/ubi9-python-3.12/pylock.toml
  runtimes/datascience/ubi9-python-3.12/pyproject.toml
  runtimes/minimal/ubi9-python-3.12/pylock.toml
  runtimes/minimal/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/pylock.toml
  runtimes/pytorch+llmcompressor/ubi9-python-3.12/pyproject.toml
  runtimes/pytorch/ubi9-python-3.12/pylock.toml
  runtimes/pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pylock.toml
  runtimes/rocm-pytorch/ubi9-python-3.12/pyproject.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/rocm-tensorflow/ubi9-python-3.12/pyproject.toml
  runtimes/tensorflow/ubi9-python-3.12/pylock.toml
  runtimes/tensorflow/ubi9-python-3.12/pyproject.toml
  tests/test_main.py
Labels: lgtm, approved, review-requested

#1538 ppc64le(runtime-datascience): sync odh-io/notebooks changes into Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: lgtm, approved, review-requested

#1568 s390x(runtime-datascience): fix pyarrow build in Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: lgtm, approved, review-requested

#1572 replace supervisord, fcgi and supervisord with httpd on the konflux dockerfile
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: lgtm, review-requested

#1579 sync missing changes for runtime dsp
  runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: lgtm, approved, review-requested

#1509 [rhoai-2.23] fix rendering of the supported configurations images table
  ci/package_versions.py
Labels: lgtm, do-not-merge/hold

#1582 RHAIENG-1247: chore(codeserver): konflux dockerfile to incorporate odh-io/notenooks changes
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: lgtm, approved, review-requested

#1584 [rhoai-2.25] cuda images should be amd64 only
  .tekton/odh-workbench-jupyter-trustyai-cpu-py312-pull-request.yaml
Labels: review-requested

#1594 update llm comp
  .tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-pull-request.yaml
  .tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9-pull-request.yaml
  .tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9-push.yaml
  delete-branches.sh
Labels: lgtm, review-requested

#1595 remove unwanted
  delete-branches.sh
Labels: lgtm, review-requested

#1596 update llm comp 3-0
  .tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-pull-request.yaml
  .tekton/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9-pull-request.yaml
  .tekton/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9-push.yaml
Labels: lgtm, review-requested

#1604 RHAIENG-1086: chore(params.env): fill in the latest known references to 2.24 images, and use registry.redhat.io/ refs
  manifests/base/commit.env
  manifests/base/params.env
Labels: lgtm, approved, review-requested

#1605 [2.25.0] fix py version on the imagestreams
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
  manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
Labels: lgtm, approved, review-requested
