Repository red-hat-data-services/notebooks, pull requests merged in 2025-08, with the labels that each got.

#1383 Add Konflux Dockerfile
  codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
Labels: lgtm, approved

#1474 remove extra not-needed dnf/curl commands from Dockerfile.konflux*
  jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
Labels: lgtm, approved, review-requested

#1476 remove extra not-needed dnf/curl commands from Dockerfile.konflux*
  jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
Labels: review-requested

#1484 updating runtime-minimal konflux image for ppc64le
  runtimes/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: review-requested

#1487 Remove more unnecessary duplicate steps
  codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
  codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: ok-to-test, review-requested

#1499 Add s390x label for building notebook images
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-pull-request.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-pull-request.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-pull-request.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py312-pull-request.yaml
Labels: review-requested

#1501 remove notebooks rhoai-2.24 pull request pipelines
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-v2-24-pull-request.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py312-v2-24-pull-request.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-v2-24-pull-request.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py312-v2-24-pull-request.yaml
Labels: review-requested

#1496 RHAIENG-540: Bump mongocli to 2.0.4 across all Konflux Dockerfiles
  jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
Labels: lgtm, review-requested

#1504 [2.24] opendatahub-io/notebooks#1976, RHOAIENG-31693: manual workaround for unimplemented commit digest sync
  manifests/base/commit-latest.env
Labels: review-requested

#1507 NO-JIRA: delete obsolete Python 3.11 `Dockerfile.konflux` files across environments in rhds/notebooks
  codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
  jupyter/trustyai/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
  runtimes/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
  runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
Labels: review-requested
