Repository red-hat-data-services/notebooks, pull requests merged in 2025-01, with the labels that each got.

#475 RHOAIENG-17774: ref(manifests): add some newlines and indentation into the json strings with package version information
  manifests/base/cuda-rstudio-buildconfig.yaml
  manifests/base/jupyter-datascience-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  manifests/base/jupyter-minimal-notebook-imagestream.yaml
  manifests/base/jupyter-pytorch-notebook-imagestream.yaml
  manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
  manifests/base/jupyter-trustyai-notebook-imagestream.yaml
  manifests/base/rstudio-buildconfig.yaml
Labels: lgtm, tide/merge-method-squash

#476 RHOAIENG-15333: chore(ci): create a Python script that reads Workbench image manifests and outputs snippet suited for inclusion in Docs
  .github/workflows/docs.yaml
  ci/package_versions.py
  ci/package_versions_selftestdata.py
  poetry.lock
  pyproject.toml
Labels: lgtm, approved

#478 RStudio: added grabbing proxy-related env vars from container context setting them in R global env file
  rstudio/rhel9-python-3.11/run-rstudio.sh
Labels: lgtm, approved

#477 RHOAIENG-17256: install necessary base OS package to make Knit rendering of R markup to PDF possible
  rstudio/rhel9-python-3.11/Dockerfile
Labels: lgtm, approved

#490 NO-JIRA: update poetry.lock file to fix broken gha ci
  poetry.lock
Labels: lgtm, approved

#499 Introduce custom sync-downstream GHA, this can handle known conflicts
  .github/pull.yml
  .github/workflows/sync-downstream.yaml
Labels: lgtm, approved, tide/merge-method-squash

#501 RHOAIENG-17368: chore(release): update the package versions script with 2.16.1 support changes
  ci/package_versions.py
Labels: lgtm, approved
