Repository red-hat-data-services/notebooks, pull requests merged in 2025-07, with the labels that each got.

#941 RHOAIENG-28184: apply runtime image via the params-latest.env using kustomize
  manifests/base/runtime-datascience-imagestream.yaml
  manifests/base/runtime-minimal-imagestream.yaml
  manifests/base/runtime-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-pytorch-imagestream.yaml
  manifests/base/runtime-rocm-tensorflow-imagestream.yaml
  manifests/base/runtime-tensorflow-imagestream.yaml
Labels: lgtm

#1044 Remove upstream tekton pipelines that incorporated on downstream by nightly sync
  .tekton/odh-pipeline-runtime-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-pipeline-runtime-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-codeserver-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-datascience-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cpu-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-minimal-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-pytorch-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-cuda-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-tensorflow-rocm-py311-ubi9-push.yaml
  .tekton/odh-workbench-jupyter-trustyai-cpu-py311-ubi9-push.yaml
Labels: lgtm, approved

#1047 Add Python 3.12 image references for ODH components in environment manifests
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: lgtm, approved

#1084 Sync latest changes on downstream manifests
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: lgtm, approved

#1085 Update and sync rhoai-2.23 branch based the latest changes for rocm-runtime-tensorflow py312 image
  manifests/base/commit-latest.env
  manifests/base/params-latest.env
Labels: approved

#1086 Fix ordering on downstream beta py312 images
  manifests/base/params-latest.env
  manifests/overlays/additional/code-server-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-datascience-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-minimal-gpu-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-minimal-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-pytorch-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-rocm-minimal-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-rocm-pytorch-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-tensorflow-notebook-imagestream-beta.yaml
  manifests/overlays/additional/jupyter-trustyai-notebook-imagestream-beta.yaml
Labels: lgtm, approved

#1257 Sync downstream `rhds:release-2024b` from `odh:2024b`
  Makefile
  jupyter/datascience/ubi9-python-3.11/Pipfile
  jupyter/datascience/ubi9-python-3.11/Pipfile.lock
  jupyter/datascience/ubi9-python-3.11/requirements.txt
  jupyter/pytorch/ubi9-python-3.11/Pipfile
  jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
  jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
  jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/tensorflow/ubi9-python-3.11/Dockerfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile
  jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
  jupyter/tensorflow/ubi9-python-3.11/requirements.txt
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
  runtimes/datascience/ubi9-python-3.11/Pipfile
  runtimes/datascience/ubi9-python-3.11/Pipfile.lock
  runtimes/datascience/ubi9-python-3.11/requirements.txt
  runtimes/pytorch/ubi9-python-3.11/Pipfile
  runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
  runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-pytorch/ubi9-python-3.11/requirements.txt
  runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile
  runtimes/rocm-tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/rocm-tensorflow/ubi9-python-3.11/requirements.txt
  runtimes/tensorflow/ubi9-python-3.11/Dockerfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile
  runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock
  runtimes/tensorflow/ubi9-python-3.11/requirements.txt
Labels: lgtm, approved

#1258 [rhoai-2.22] RHOAIENG-30247: Bump transformers version from 4.49.0 to 4.52.1
  jupyter/trustyai/ubi9-python-3.11/Pipfile
  jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
  jupyter/trustyai/ubi9-python-3.11/requirements.txt
Labels: lgtm

#1315 [2.22] update `setuptools` to version 78.1.1 in RStudio Pipfiles; run `dnf install` to reduce fixable base image vulnerabilities
  Makefile
  rstudio/c9s-python-3.11/Dockerfile.cpu
  rstudio/c9s-python-3.11/Dockerfile.cuda
  rstudio/c9s-python-3.11/Pipfile
  rstudio/c9s-python-3.11/Pipfile.lock
  rstudio/c9s-python-3.11/requirements.txt
  rstudio/rhel9-python-3.11/Dockerfile.cpu
  rstudio/rhel9-python-3.11/Dockerfile.cuda
  rstudio/rhel9-python-3.11/Pipfile
  rstudio/rhel9-python-3.11/Pipfile.lock
  rstudio/rhel9-python-3.11/requirements.txt
Labels: lgtm, tide/merge-method-rebase
